app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_cors import CORS

from .site.routes import site
from .authentication.routes import auth
from .api.open_weather import open_weather
from config import Config
from models import marsh, sqla, login_manager
from helpers import Encoding

app = Flask(__name__)
CORS(app)

if __name__ == '__main__':
	app.run(debug=False)

app.register_blueprint(site)
app.register_blueprint(auth)

app.register_blueprint(open_weather)

app.json_encoder = Encoding

app.config.from_object(Config)
app.config['SESSION_TYPE'] = 'filesystem'
sqla.init_app(app)
login_manager.init_app(app)
marsh.init_app(app)
migrate = Migrate(app, sqla)

app/api/routes.py
from flask import Blueprint, request, jsonify

from helpers import token_required
from models import sqla, FavoriteCities, city_schema, cities_schema, User

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/addcity', methods=['POST'])
@token_required
def addcity(current_user_token):
    id = request.json['id']
    city = request.json['city']
    user_id = current_user_token.id

    new_city = FavoriteCities(id = id,
                              city = city,
                              user_id=user_id)
    
    sqla.session.add(new_city)
    sqla.commit()
    response = city_schema.dump(new_city)
    return jsonify(response)

app/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user

from forms import CreateUser, UserLogin
from models import sqla, check_password_hash, User

auth = Blueprint('auth', __name__, template_folder='auth_pages')

@auth.route('/sign_up', methods = ['GET','POST'])
def sign_up():
    form = CreateUser()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            user_city = form.user_city.data
            f_name = form.f_name.data
            l_name = form.l_name.data

            user = User(email = email, password = password, 
                        user_city = user_city, f_name = f_name, l_name = l_name)
            
            sqla.session.add(user)
            sqla.session.commit()

            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid form data, please check your form')
    
    return render_template('sign_up.html', form=form)

@auth.route('/sign_in', methods = ['GET', 'POST'])
def sign_in():
    form = UserLogin()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                print(f'{email} logged in now')
                return redirect(url_for('site.profile'))
            else:
                return redirect(url_for('auth.sign_in', form = form))
    except:
        raise Exception('Invalid form data, please check your information')
    
    return render_template('sign_in.html', form = form)

@auth.route('/sign_out')
def sign_out():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for
import requests
from datetime import datetime

from ..api.open_weather import weather, api_key, daily
from ..assets.weekday_dict import weekdays
from models import User, FavoriteCities, login_manager, sqla, cities_schema, city_schema
from forms import AddFavCity, DelFavCity
from helpers import token_required
import flask_login
from flask_login import current_user, login_required

site = Blueprint('site',__name__, template_folder='site_pages')

@site.route('/')
@site.route('/home')
def home():
    day = datetime.now().weekday()
    return render_template('index.html', weather = weather, daily = daily, weekdays = weekdays, day = day)

@site.route('/about')
def about():
    return render_template('about.html')


@site.route('/profile', methods = ['POST','GET'])
@login_required
def profile():
    user = User()
    form = AddFavCity()
    day = datetime.now().weekday()


    # gets the daily forecast for the user's city, entered when creating a profile
    find_user = user.query.get(current_user.id)
    user_profile_city = find_user.user_city
    user_city_weather = requests.get(f'https://api.openweathermap.org/data/2.5/weather?q={user_profile_city}&appid={api_key}&units=imperial').json()
    
    # API errors
    # TODO: build out more specific error responses
    errors =['400','401','404','429','5xx']

    if user_city_weather['cod'] not in errors:
        user_city_weather = requests.get(f'https://api.openweathermap.org/data/2.5/weather?q={user_profile_city}&appid={api_key}&units=imperial').json()
        user_daily = requests.get(f'https://api.openweathermap.org/data/3.0/onecall?lat={user_city_weather["coord"]["lat"]}&lon={user_city_weather["coord"]["lon"]}&appid={api_key}&units=imperial').json()

    else:
        user_daily = ''

    
    current_id = flask_login.current_user.get_id()
    user_cities = FavoriteCities.query.filter_by(user_id = current_id).all()

    if len(user_cities)>0:
        fav_city_weather = [requests.get(f'https://api.openweathermap.org/data/2.5/weather?q={i}&appid={api_key}&units=imperial').json() for i in user_cities]
    
    else:
        fav_city_weather = None


    #holder dictionary to shorten list of variables being passed to profile.html
    holder_dict = {
        'fav_city_weather': fav_city_weather,
        'user_daily': user_daily,
        'form': form,
        'weekdays': weekdays,
        'day': day
    }

    # pulling city entered into search bar
    user_input = request.form
    
    if request.method == 'POST': # and form.validate_on_submit():
        print('in the try if')

        address_list = user_input.getlist('city')
        address = address_list[0].split(',')
        city = address[0]

        new_city = FavoriteCities(city = city, user_id = current_id)
        sqla.session.add(new_city)
        sqla.session.commit()
        response = city_schema.dump(new_city)
        return redirect('/profile')


    return render_template('profile.html', user = user, holder_dict = holder_dict)


@site.route('/edit.html', methods = ['GET','POST','DELETE'])
@login_required
def edit():
    user = User()
    form = DelFavCity()
    current_id = flask_login.current_user.get_id()
    user_cities = FavoriteCities.query.filter_by(user_id = current_id).all()        
    return render_template('edit.html', user = user, form = form, user_cities = user_cities)


@site.route('/edit/<id>', methods = ['DELETE', 'POST'])
def delete_item(id):
    selected_city = FavoriteCities.query.filter_by(id = id).first()
    if request.form.get('_method') == 'DELETE':  #and form.validate_on_submit()
        sqla.session.delete(selected_city)
        sqla.session.commit()
        response = city_schema.dump(selected_city)
        print('item deleted successfully')

    else:
        new_city_name = request.form.get('city_name')
        print('new city name', new_city_name)
        selected_city.city = new_city_name
        sqla.session.commit()

    return redirect(url_for('site.profile'))


@site.route('/maps')
def maps():
    return render_template('maps.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{{url_for('static',filename='dist/css/output.css')}}">
    <title>Your Weather</title>
    <!-- GOOGLE MAPS -->
    <script>
        (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({
          key: "AIzaSyAEjS4jEmB1nDmtnqRAuJBCc5eOvltXbOw",
          v: "weekly",
          // Use the 'v' parameter to indicate the version to use (weekly, beta, alpha, etc.).
          // Add other bootstrap parameters as needed, using camel case.
        });
      </script>

    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <!-- INITIALIZING MAPS -->



    <!-- END GOOGLE MAPS -->

</head>
<body>
    <nav class="bg-indigo-dye px-2 sm:px-4 py-2.5">
        <div class="container flex flex-wrap items-center justify-between mx-auto">
            <a href="{{url_for ('site.home')}}" class="flex items-center">
                <img src="../static/your_weather_logo_light.png" class="h-6 mr-3 sm:h-9" alt="Your Weather Logo">
            </a>
            <div class="flex md:order-2">

                <button data-collapse-toggle="navbar-cta" type="button"
                    class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
                    aria-controls="navbar-cta" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                            clip-rule="evenodd"></path>
                    </svg>
                </button>
            </div>
            <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-cta">
                <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 
                    md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 
                    md:bg-white">
                    <li>
                        <a href="{{ url_for('site.home')}}" 
                        class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded 
                        md:bg-transparent md:text-blue-700 md:p-0"
                        aria-current="page">
                            Home
                        </a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li>
                        <a href="{{ url_for('site.profile') }}"
                        class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 
                        md:hover:bg-transparent md:hover:text-blue-700 md:p-0 ">
                            Profile
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('auth.sign_out') }}"
                        class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 
                        md:hover:bg-transparent md:hover:text-blue-700 md:p-0 ">
                            Sign Out
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{{ url_for('auth.sign_up') }}"
                        class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 
                        md:hover:bg-transparent md:hover:text-blue-700 md:p-0 ">
                            Sign Up
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('auth.sign_in') }}"
                        class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 
                        md:hover:bg-transparent md:hover:text-blue-700 md:p-0 ">
                            Sign In
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>

</body>
</html>